Fixed a bug where get_user_home_dir() would not be found on Linux
SutekhVRC/VOR pull request #6
Opened 2023-11-06 21:02 UTC by dfgHiatus

Using Debian 12.2. Looks like the inclusion of the `use crate::vorutils::get_user_home_dir;` header in `ui.rs` and `config.rs` took care of things for me, hope this helps anyone else!

2023-11-09 19:58 UTC, SutekhVRC requested changes
Oops! forgot to add linux pieces during config path changes!
Thank you for submitting this, could you change the imports to work by platform like this and resubmit!

```
#[cfg(target_os = "linux")]
use crate::vorutils::get_user_home_dir;
```

2023-11-09 20:00 UTC, dfgHiatus commented
Sure thing! I'm away from my PC for the weekend, but when I get back I'll make those changes 👍

2023-11-13 20:29 UTC, dfgHiatus commented
Added in [048dd28](https://github.com/SutekhVRC/VOR/pull/6/commits/048dd28814656612e0d2a1cd43272bfb3866b0b5)

2023-11-16 18:15 UTC, merged

2023-11-16 18:16 UTC, SutekhVRC commented
Thanks!